language: java
jdk: openjdk11
env:
  global:
  - secure: b4Dyx4fuWoHPt2m7WcVw26QcqPVeOQnVkAa8ssbHl38hMRsFJeea2RN05jCpkxEIa4CCPhGukQpRkyohcgbHCGt6sWCGbfIDh63DBuY3T9fZmSkMd8FuqOdWFejOwAjO4uvdVPI4vcAMxnEEhQv5o9HjwKbcLGvd7asJkk0Q0JK4ih6coF0IUWwmAIJ2lP7DCFWUN9GpTikluleDwMiPF0i74PkPnZY2h7V0Y8TBrZU5nlfZGR5x9XkZ44fDNpqB4KZpNefVDCZ97YRnA7KsiAJ3XsZw8qak3hA2a6QOjsuJXhy4doLTNxk/YlAA0HfX+cJ14VhBoBAio5agyb21Ils7Gv000A8cb325anVKCYlfwoXed5eMk9Z3V20bSIrMSAhwCOJfHJqIGY2gBsxUq0sq3+m8Ln7faPMYswdS/VqEGVlJ5VDHD8RgCC6dQISCys7P4l3sKNSoAD+oJuABnFiCzcFxhsF0uA/DHOmYw/8+Kipt15s7DiZ1x03+2IGp5gshke2SQRWRjWi6LfVV8yJaqj6M1IT7Rq37hNUkG39T0PabIGsKNQ8OtrkUoiyh+9xFJJ2zrDIlW5jGtpcPHqpTxKUwZvL8se2O3J9oRp5Ddns9UxtF5BJuhGVMV2XG7LFKwf8MuMbKXI4ymFlf0evWCVZOiszyfdnxbNkd4KQ=
  - secure: ja/ONZ6WbmTnP+mCq54UtNRy7aiFy2o7ytC8ostmPUocRsD+G36v6bKS4VLpMQeLrPJ1GO+LTXxaGtWs4SzNtDXiXD2H8lfMwiDkAukYwsS1fv9LBGwlHvCtOCBWbgbPQNA2A/0l9MhOpXt9EF/9Bo0dcz7idy8H80LxnaaX2QFyncHm1EPNd2++kvM5Fx6ryKVpQNuGIXUGiiUm8qzVp4lY8/xrnNspUdV5A+fdtLex0B2lTyQuVlZ7VBihkPjI/alpZ1KhYgIm4c6vVQttBboT1NMZjg+1o3yrr0k8HQNDd/BBkqFSGK7w//i9xGkG3VDjl2pecEwC+vKL/9F5RNdc0/5E1gp8o7QSAh8yEb1xPotTshGkrZ0slahbMISv4vXGe9r3zCKyrXG6Tz40245PWNiFK4KQv3IFqvA/GSvzHlcsZsQ8/iAd9U70O2O9hsDYB1Fzog1AOKfIivDi6MJmTBwsjO/c/utYRpt3jiSydX8LNEMZ8TO9MjxisVEHOTBpJPy3X/jlxNf5jaJG1Z68b/S7QyhLDYFFQJPJAjUQBSKE9MXsynEZYpRjnu5NzLG/lSFDD03C3Y3fs1A8BZoKy44lwp8bYCncMDGZKp/7nMy8yhHkUhzBnrIBppCyY96KeLlGc5moB8mu0kO8exUso8VuJ8zHU5dCn/fdYiY=
install: skip
script: mvn --settings .mvn/settings.xml install && ([[ $TRAVIS_BRANCH != "master" ]] || mvn --settings .mvn/settings.xml -DskipTests=true deploy)
sudo: false
cache:
  directories: "$HOME/.m2"
branches:
  except: gh-pages
notifications:
  email: joerg.hohwiller@googlemail.com
